# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b556d12cda53b8c79b571cbb4a28e05fe7ead66d5bfd20ebefd06af443a558d82aa7a9b334bdb39badca25ee6cf224a9a28edc53edd03bf0e87f2f5de4c4af1

test:
  secret_key_base: 538b3115ed5286b36e7ced543ddef8a68d5114a0e9d9bf05e1fad2ed0f56302611fd3ce0745414554e21552b9a6df39b2364c29d30302f2f142eec02696b7d4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
